### PR TITLE
Enabling build in docker container

### PR DESCRIPTION
**Pull request by mikn**
This is to allow you to use automated build services such as them provided by Quay and Docker Hub. :)

### CODE REVIEW

**Comment by andrewhowdencom** [comment]
This has two from directives; I've never seen that before. Is it syntatically valid?

**Comment by mikn** [comment]
Ah, yes. It is using a new-ish docker feature called "multi-stage build". For reference, see here: https://docs.docker.com/engine/userguide/eng-image/multistage-build/

**Comment by bakins** [comment]
@mikn Sorry for the delay in reviewing this. This looks good. Let me test it on my side and then I'll merge.

**Comment by bakins** [comment]
thanks @mikn !

**Pull request merged**
